name: Mason Fox
title: Front-End Web Developer

author: Mason Fox
# Email uses formspree.io, just add your email here! (http://formspree.io/)
email: masonfox22@gmail.com

permalink: /blog/:title/

paginate: 3
paginate_path: blog/page:num

markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

gems: [jekyll-paginate]
